# Generated by Django 4.0 on 2021-12-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['created_at']},
        ),
    ]
